# El método de k-means

In [12]:
import numpy as np

In [13]:
data = np.random.random(90).reshape(30,3)
data

array([[0.03226662, 0.18620415, 0.10081182],
       [0.69129664, 0.6139198 , 0.44159786],
       [0.77415384, 0.82004097, 0.77974966],
       [0.85433268, 0.70524993, 0.52725234],
       [0.6947959 , 0.98559267, 0.33831582],
       [0.14783753, 0.22192442, 0.70945717],
       [0.37993592, 0.86454053, 0.74698318],
       [0.38057488, 0.00641267, 0.75510546],
       [0.69188758, 0.86121691, 0.72462447],
       [0.74273045, 0.00665594, 0.85292754],
       [0.65609489, 0.57458432, 0.32574414],
       [0.63703049, 0.6742395 , 0.9638552 ],
       [0.99004931, 0.60355406, 0.14778189],
       [0.66859588, 0.21863081, 0.3778456 ],
       [0.16219762, 0.24146896, 0.75017484],
       [0.73804708, 0.69816477, 0.8924324 ],
       [0.52071839, 0.2334488 , 0.74985544],
       [0.54123183, 0.93861279, 0.58344786],
       [0.49698988, 0.21191384, 0.09759696],
       [0.98513091, 0.16964751, 0.84412829],
       [0.17829622, 0.52755952, 0.52432214],
       [0.75049068, 0.34942331, 0.2515998 ],
       [0.

In [14]:
c1 = np.random.choice(range(len(data)))
c2 = np.random.choice(range(len(data)))
clust_centers = np.vstack([data[c1], data[c2]])
clust_centers

array([[0.72696329, 0.91196724, 0.91471848],
       [0.03226662, 0.18620415, 0.10081182]])

In [15]:
from scipy.cluster.vq import vq

In [16]:
clusters = vq(data, clust_centers)
clusters

(array([1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1,
        1, 0, 0, 0, 0, 0, 0, 1]),
 array([0.        , 0.56031019, 0.16998226, 0.45725815, 0.58197548,
        0.62054954, 0.38834575, 0.7627213 , 0.19985403, 0.90755456,
        0.68245171, 0.25887604, 0.8674818 , 0.69477632, 0.66453637,
        0.21524641, 0.72808245, 0.38071825, 0.46544498, 0.78909574,
        0.56321321, 0.75181335, 0.42470558, 0.73642599, 0.63203073,
        0.        , 0.58380301, 0.12452599, 0.79738983, 0.31401646]))

In [17]:
labels = clusters[0]
labels

array([1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 1])

In [18]:
import plotly.plotly as py
import plotly.graph_objs as go
import plotly.offline as ply

ImportError: 
The plotly.plotly module is deprecated,
please install the chart-studio package and use the
chart_studio.plotly module instead. 


In [11]:
x = []
y = []
z = []
x2 = []
y2 = []
z2 = []

for i in range(0, len(labels)):
    if(labels[i] == 0):
        x.append(data[i,0])
        y.append(data[i,1])
        z.append(data[i,2])
        
    else:
        x2.append(data[i,0])
        y2.append(data[i,1])
        z2.append(data[i,2])

cluster1 = go.Scatter3d(
    x=x,
    y=y,
    z=z,
    mode='markers',
    marker=dict(
        size=12,
        line=dict(
            color='rgba(217, 217, 217, 0.14)',
            width=0.5
        ),
        opacity=0.9
    ),
    name="Cluster 0"
)


cluster2 = go.Scatter3d(
    x=x2,
    y=y2,
    z=z2,
    mode='markers',
    marker=dict(
        color='rgb(127, 127, 127)',
        size=12,
        symbol='circle',
        line=dict(
            color='rgb(204, 204, 204)',
            width=1
        ),
        opacity=0.9
    ),
    name="Cluster 1"
)
data2 = [cluster1, cluster2]
layout = go.Layout(
    margin=dict(
        l=0,
        r=0,
        b=0,
        t=30
    )
)

fig = go.Figure(data=data2, layout=layout)
ply.plot(fig, filename='Clusters')


NameError: name 'go' is not defined

In [14]:
from scipy.cluster.vq import kmeans

In [9]:
kmeans(data, clust_centers)

(array([[0.55149309, 0.14895199, 0.50973511],
        [0.59158003, 0.69692438, 0.50948822]]), 0.38784900251440213)

In [10]:
kmeans(data, 2)

(array([[0.55511363, 0.20456483, 0.5587382 ],
        [0.59603233, 0.75078951, 0.45343179]]), 0.3860151283499985)